DROP TABLE IF EXISTS DIET_REQUESTS;
DROP TABLE IF EXISTS WORKOUT_REQUESTS;
DROP TABLE IF EXISTS NUTRITIONIST_COLLABORATIONS;
DROP TABLE IF EXISTS TRAINER_COLLABORATIONS;
DROP TABLE IF EXISTS NUTRITIONISTS;
DROP TABLE IF EXISTS ATHLETES;
DROP TABLE IF EXISTS TRAINERS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS( 
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_TYPE CHAR (1) NOT NULL,
    NAME VARCHAR (50) NOT NULL, 
    SURNAME VARCHAR (50) NOT NULL, 
    BIRTHDATE DATE NOT NULL,
    GENDER CHAR (1) NOT NULL,
    USERNAME VARCHAR (50) NOT NULL, 
    PASSWORD VARCHAR (50) NOT NULL,
    CONSTRAINT USER_TYPE_CONSTRAINT CHECK(USER_TYPE = 'T' OR USER_TYPE = 'N' OR USER_TYPE = 'A')
);

CREATE TABLE TRAINERS( 
    TRAINER_ID INT PRIMARY KEY,
    TITLE VARCHAR (50) NOT NULL,
    DESCRIPTION VARCHAR (200) NOT NULL,
    FOREIGN KEY (TRAINER_ID) REFERENCES USERS (USER_ID)  
);

CREATE TABLE NUTRITIONISTS( 
    NUTRITIONIST_ID INT PRIMARY KEY,
    TITLE VARCHAR (50) NOT NULL,
    DESCRIPTION VARCHAR (200) NOT NULL,
    FOREIGN KEY (NUTRITIONIST_ID) REFERENCES USERS (USER_ID)  
);

CREATE TABLE ATHLETES( 
    ATHLETE_ID INT PRIMARY KEY,
    HEIGHT FLOAT NOT NULL,
    WEIGHT FLOAT NOT NULL,
    SPORT VARCHAR (50),
    FOREIGN KEY (ATHLETE_ID) REFERENCES USERS (USER_ID)  
);

CREATE TABLE TRAINER_COLLABORATIONS( 
    COLLABORATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    ATHLETE_ID INT NOT NULL,
    TRAINER_ID INT NOT NULL,
    INIT_DATE DATE NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    FOREIGN KEY (ATHLETE_ID) REFERENCES ATHLETES (ATHLETE_ID), 
    FOREIGN KEY (TRAINER_ID) REFERENCES TRAINERS (TRAINER_ID),
    CONSTRAINT UNIQUE_TRAINER_COLLABORATION_CONSTRAINT UNIQUE (TRAINER_ID, ATHLETE_ID)
);

CREATE TABLE NUTRITIONIST_COLLABORATIONS( 
    COLLABORATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    ATHLETE_ID INT NOT NULL,
    NUTRITIONIST_ID INT NOT NULL,
    INIT_DATE DATE NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    FOREIGN KEY (ATHLETE_ID) REFERENCES ATHLETES (ATHLETE_ID),
    FOREIGN KEY (NUTRITIONIST_ID) REFERENCES NUTRITIONISTS (NUTRITIONIST_ID), 
    CONSTRAINT UNIQUE_NUTRITIONIST_COLLABORATION_CONSTRAINT UNIQUE (NUTRITIONIST_ID, ATHLETE_ID)
);


CREATE TABLE WORKOUT_REQUESTS( 
    REQUESTS_ID INT AUTO_INCREMENT PRIMARY KEY,
    COLLABORATION_ID INT NOT NULL,
    REQUEST_DATE DATE NOT NULL,
    HEALTH_NOTES VARCHAR (200),
    WORKOUT_GOAL VARCHAR (300) NOT NULL,
    WORKOUT_DAYS INT NOT NULL,
    WORKOUT_JSON JSON,
    FOREIGN KEY (COLLABORATION_ID) REFERENCES TRAINER_COLLABORATIONS (COLLABORATION_ID),
    CONSTRAINT WORKOUT_DAYS_CONSTRAINT CHECK(WORKOUT_DAYS <= 7)
);


CREATE TABLE DIET_REQUESTS( 
    REQUESTS_ID INT AUTO_INCREMENT PRIMARY KEY,
    COLLABORATION_ID INT NOT NULL,
    REQUEST_DATE DATE NOT NULL,
    ALLERGIES VARCHAR (200),
    INTOLERANCES VARCHAR (200),
    BASAL_METABOLIC_RATE INT,
    DIET_GOAL VARCHAR (300) NOT NULL,
    LIFESTYLE INT NOT NULL,
    DIET_JSON JSON,
    FOREIGN KEY (COLLABORATION_ID) REFERENCES NUTRITIONIST_COLLABORATIONS (COLLABORATION_ID),
    CONSTRAINT LIFESTYLE_CONSTRAINT CHECK(LIFESTYLE <= 5 AND LIFESTYLE >= 1)
);

INSERT INTO USERS (USER_TYPE, NAME, SURNAME, BIRTHDATE, GENDER, USERNAME, PASSWORD)
VALUES
    ('A','Stefano', 'Faccio', '2000-11-04', 'M', 'stefanotrick', 'stefanotrick'),
    ('B','Giovanni', 'Faccio', '2000-11-04', 'M', 'stefanotrick', 'stefanotrick');
